### PR TITLE
Multiple Improvements

### PR DESCRIPTION
**Pull request by TheGreenBandit**
[+] Added Spawning Objects (host)
[+] Added Deleting Objects
[+] Added Changing Object Value
[+] Added if a player is host in the playerlist
[+] Added issue templates to clean up repo
[+] Added untargetable
[/] Changed source directory

TODO
if we want to have the client without host be able to spawn shit we would need to figure out a bypass, leaving my non working method in so others can get an idea, SpawnNetworkObjectLocallyCommon in NetworkSpawnManager might allow for bypassing host but i dont wanna look into it

### CODE REVIEW

**Comment by chuxiaaaa** [comment]
I have tried, but both generating and deleting items only take effect on the console. Good luck

**Comment by TheGreenBandit** [comment]
> I have tried, but both generating and deleting items only take effect on the host. Good luck

Im thinking if we patch the check if host it should work just fine when spawning, just gotta find which function actually checks if you are host

**Comment by chuxiaaaa** [comment]
```
> > I have tried, but both generating and deleting items only take effect on the host. Good luck
> 
> Im thinking if we patch the check if host it should work just fine when spawning, just gotta find which function actually checks if you are host

I think the reason for the invalidation is the process issue. The process of the game is: server generates items/enemies/monsters -> notifies client -> client generates items/enemies/monsters. This is why it only takes effect on the host, because the client cannot notify the client, and if the client notifies the server, it will be intercepted by the server's local code. However, it is obviously impossible for us to modify the local code of the host.

This is the intercepted code


`if (base.OwnerClientId != networkManager.LocalClientId)
{
	if (networkManager.LogLevel <= Unity.Netcode.LogLevel.Normal)
	{
		Debug.LogError("Only the owner can invoke a ServerRpc that requires ownership!");
	}
	return;
}
`
```

**Comment by chuxiaaaa** [comment]
```
private static void \_\_rpc\_handler\_1482204640(NetworkBehaviour target, FastBufferReader reader, \_\_RpcParams rpcParams)
    {
        NetworkManager networkManager = target.NetworkManager;
        if (networkManager == null || !networkManager.IsListening)
        {
            return;
        }
        if (rpcParams.Server.Receive.SenderClientId != target.OwnerClientId)
        {
            if (networkManager.LogLevel <= Unity.Netcode.LogLevel.Normal)
            {
                Debug.LogError("Only the owner can invoke a ServerRpc that requires ownership!");
            }
            return;
        }
        target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.Server;
        ((StartOfRound)target).ManuallyEjectPlayersServerRpc();
        target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.None;
    }
```
This is the execution program that receives the server notification

**Comment by TheGreenBandit** [comment]
> ```
> private static void \_\_rpc\_handler\_1482204640(NetworkBehaviour target, FastBufferReader reader, \_\_RpcParams rpcParams)
>     {
>         NetworkManager networkManager = target.NetworkManager;
>         if (networkManager == null || !networkManager.IsListening)
>         {
>             return;
>         }
>         if (rpcParams.Server.Receive.SenderClientId != target.OwnerClientId)
>         {
>             if (networkManager.LogLevel <= Unity.Netcode.LogLevel.Normal)
>             {
>                 Debug.LogError("Only the owner can invoke a ServerRpc that requires ownership!");
>             }
>             return;
>         }
>         target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.Server;
>         ((StartOfRound)target).ManuallyEjectPlayersServerRpc();
>         target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.None;
>     }
> ```
> 
> This is the execution program that receives the server notification

now that i think about it most functions such as the spawn check if the player is host by comparing a instance of localclientid such as in NetworkObject

```
        public bool IsLocalPlayer
        {
            get
            {
                if (NetworkManager != null && IsPlayerObject)
                {
                    return OwnerClientId == NetworkManager.LocalClientId;
                }

                return false;
            }
        }
        ```
        if we can write to the localclient id and just change it to the host's when we call a function that requires host and restore it it should work fine

**Comment by chuxiaaaa** [comment]
> > ```
> > private static void \_\_rpc\_handler\_1482204640(NetworkBehaviour target, FastBufferReader reader, \_\_RpcParams rpcParams)
> >     {
> >         NetworkManager networkManager = target.NetworkManager;
> >         if (networkManager == null || !networkManager.IsListening)
> >         {
> >             return;
> >         }
> >         if (rpcParams.Server.Receive.SenderClientId != target.OwnerClientId)
> >         {
> >             if (networkManager.LogLevel <= Unity.Netcode.LogLevel.Normal)
> >             {
> >                 Debug.LogError("Only the owner can invoke a ServerRpc that requires ownership!");
> >             }
> >             return;
> >         }
> >         target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.Server;
> >         ((StartOfRound)target).ManuallyEjectPlayersServerRpc();
> >         target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.None;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is the execution program that receives the server notification
> 
> now that i think about it most functions such as the spawn check if the player is host by comparing a instance of localclientid such as in NetworkObject
> 
> ```
>         public bool IsLocalPlayer
>         {
>             get
>             {
>                 if (NetworkManager != null && IsPlayerObject)
>                 {
>                     return OwnerClientId == NetworkManager.LocalClientId;
>                 }
> 
>                 return false;
>             }
>         }
>         ```
>         if we can write to the localclient id and just change it to the host's when we call a function that requires host and restore it it should work fine
> ```

I think it's just tricking yourself, because other clients don't think you are the host, so they won't execute the commands you send

**Comment by TheGreenBandit** [comment]
> > > ```
> > > private static void \_\_rpc\_handler\_1482204640(NetworkBehaviour target, FastBufferReader reader, \_\_RpcParams rpcParams)
> > >     {
> > >         NetworkManager networkManager = target.NetworkManager;
> > >         if (networkManager == null || !networkManager.IsListening)
> > >         {
> > >             return;
> > >         }
> > >         if (rpcParams.Server.Receive.SenderClientId != target.OwnerClientId)
> > >         {
> > >             if (networkManager.LogLevel <= Unity.Netcode.LogLevel.Normal)
> > >             {
> > >                 Debug.LogError("Only the owner can invoke a ServerRpc that requires ownership!");
> > >             }
> > >             return;
> > >         }
> > >         target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.Server;
> > >         ((StartOfRound)target).ManuallyEjectPlayersServerRpc();
> > >         target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.None;
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This is the execution program that receives the server notification
> > 
> > 
> > now that i think about it most functions such as the spawn check if the player is host by comparing a instance of localclientid such as in NetworkObject
> > ```
> >         public bool IsLocalPlayer
> >         {
> >             get
> >             {
> >                 if (NetworkManager != null && IsPlayerObject)
> >                 {
> >                     return OwnerClientId == NetworkManager.LocalClientId;
> >                 }
> > 
> >                 return false;
> >             }
> >         }
> >         ```
> >         if we can write to the localclient id and just change it to the host's when we call a function that requires host and restore it it should work fine
> > ```
> 
> I think it's just tricking yourself, because other clients don't think you are the host, so they won't execute the commands you send

maybe, it will have to be tested, let me see if i can write something up quick and if you have anyone to test with try it

**Comment by chuxiaaaa** [comment]
> > > > ```
> > > > private static void \_\_rpc\_handler\_1482204640(NetworkBehaviour target, FastBufferReader reader, \_\_RpcParams rpcParams)
> > > >     {
> > > >         NetworkManager networkManager = target.NetworkManager;
> > > >         if (networkManager == null || !networkManager.IsListening)
> > > >         {
> > > >             return;
> > > >         }
> > > >         if (rpcParams.Server.Receive.SenderClientId != target.OwnerClientId)
> > > >         {
> > > >             if (networkManager.LogLevel <= Unity.Netcode.LogLevel.Normal)
> > > >             {
> > > >                 Debug.LogError("Only the owner can invoke a ServerRpc that requires ownership!");
> > > >             }
> > > >             return;
> > > >         }
> > > >         target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.Server;
> > > >         ((StartOfRound)target).ManuallyEjectPlayersServerRpc();
> > > >         target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.None;
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > This is the execution program that receives the server notification
> > > 
> > > 
> > > now that i think about it most functions such as the spawn check if the player is host by comparing a instance of localclientid such as in NetworkObject
> > > ```
> > >         public bool IsLocalPlayer
> > >         {
> > >             get
> > >             {
> > >                 if (NetworkManager != null && IsPlayerObject)
> > >                 {
> > >                     return OwnerClientId == NetworkManager.LocalClientId;
> > >                 }
> > > 
> > >                 return false;
> > >             }
> > >         }
> > >         ```
> > >         if we can write to the localclient id and just change it to the host's when we call a function that requires host and restore it it should work fine
> > > ```
> > 
> > 
> > I think it's just tricking yourself, because other clients don't think you are the host, so they won't execute the commands you send
> 
> maybe, it will have to be tested, let me see if i can write something up quick and if you have anyone to test with try it



> > > > ```
> > > > private static void \_\_rpc\_handler\_1482204640(NetworkBehaviour target, FastBufferReader reader, \_\_RpcParams rpcParams)
> > > >     {
> > > >         NetworkManager networkManager = target.NetworkManager;
> > > >         if (networkManager == null || !networkManager.IsListening)
> > > >         {
> > > >             return;
> > > >         }
> > > >         if (rpcParams.Server.Receive.SenderClientId != target.OwnerClientId)
> > > >         {
> > > >             if (networkManager.LogLevel <= Unity.Netcode.LogLevel.Normal)
> > > >             {
> > > >                 Debug.LogError("Only the owner can invoke a ServerRpc that requires ownership!");
> > > >             }
> > > >             return;
> > > >         }
> > > >         target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.Server;
> > > >         ((StartOfRound)target).ManuallyEjectPlayersServerRpc();
> > > >         target.\_\_rpc\_exec\_stage = NetworkBehaviour.\_\_RpcExecStage.None;
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > This is the execution program that receives the server notification
> > > 
> > > 
> > > now that i think about it most functions such as the spawn check if the player is host by comparing a instance of localclientid such as in NetworkObject
> > > ```
> > >         public bool IsLocalPlayer
> > >         {
> > >             get
> > >             {
> > >                 if (NetworkManager != null && IsPlayerObject)
> > >                 {
> > >                     return OwnerClientId == NetworkManager.LocalClientId;
> > >                 }
> > > 
> > >                 return false;
> > >             }
> > >         }
> > >         ```
> > >         if we can write to the localclient id and just change it to the host's when we call a function that requires host and restore it it should work fine
> > > ```
> > 
> > 
> > I think it's just tricking yourself, because other clients don't think you are the host, so they won't execute the commands you send
> 
> maybe, it will have to be tested, let me see if i can write something up quick and if you have anyone to test with try it

Good luck. I'm going to bed. I'll wait for your good news.

**Comment by TheGreenBandit** [comment]
just  pushed a mockup, try it once you are able to

**Comment by TheGreenBandit** [comment]
might have to change name of pr with how much im adding lol

**Comment by zfs266192** [comment]
Items can be generated but cannot be picked up.

**Comment by TheGreenBandit** [comment]
> Items can be generated but cannot be picked up.

Nice! All we need to do then is set the item in the inventory then and we have it? Does it retain its scrap balue? Have you tried spawning enemies?

**Comment by realbillie** [comment]
Back to Minecraft hack days in factions lmao. Remember the whole set offhand thing. That's what this vibe gives me.

**Comment by zfs266192** [comment]
Cant spawn enemies without host

**Comment by zfs266192** [comment]
螢幕擷取畫面 2024-01-23 222845
like this cant pick up

**Comment by zfs266192** [comment]
ok

**Comment by zfs266192** [comment]
same cant pick up

**Comment by zfs266192** [comment]
螢幕擷取畫面 2024-01-23 223554
Still cant pick up

**Comment by chuxiaaaa** [comment]
According to the above rpc_handler method, I believe we cannot succeed because the code to determine whether the host is on another player is in the client side, but we cannot modify the code of other clients.

**Comment by TheGreenBandit** [comment]
All we should need to do is set it into the players hands after spawning, then it should be fine

**Comment by chuxiaaaa** [comment]
Sounds like a feasible method. I will try it

**Comment by TheGreenBandit** [comment]
try this

**Comment by zfs266192** [comment]
Cant grab. I think only the host can get it

**Comment by zfs266192** [comment]
Can spawn but dont have permission to take it

**Comment by zfs266192** [comment]
I tried ....   But it still cant pick up to my inventory

**Comment by zfs266192** [comment]
螢幕擷取畫面 2024-01-23 223554
It should have purple characters

**Comment by zfs266192** [comment]
Can you try using gift boxes to generate items?

**Comment by TheGreenBandit** [comment]
try this, spawning enemy might work now

**Comment by TheGreenBandit** [comment]
hm, for the planned feature in the readme if we just get the enemies, patch their update function with 
```
 if(notargetme && enemy.targetplayer == localplayer)
 {
 enemy.targetplayer = get the closest other player
}
```
that should be it

**Comment by TheGreenBandit** [comment]
hmm why tf is this shit not letting me use mouse in gui, or any features like noclip working now

**Comment by TheGreenBandit** [comment]
did not mean to close

**Comment by TheGreenBandit** [comment]
> Can you try using gift boxes to generate items?

that may work, except how would we spawn the gift box

**Comment by zfs266192** [comment]
Your menu is broken and none of the functions work.

**Comment by zfs266192** [comment]
Still cant grab items

**Comment by TheGreenBandit** [comment]
> Your menu is broken and none of the functions work. New version

Do you know which commit did it? Did it work before the recent commits?

**Comment by zfs266192** [comment]
commit 35b2627 doesnt work

**Comment by zfs266192** [comment]
commit a7c6bf0 works

**Comment by zfs266192** [comment]
But still cant grab items

**Comment by TheGreenBandit** [comment]
Ok good to know, i will have to see about different ways of getting the object to go into inventory

**Comment by zfs266192** [comment]
Thank you for doing this

**Comment by TheGreenBandit** [comment]
just fixed the menu, i do see the problem, even when host you cannot pick up the item.

**Comment by TheGreenBandit** [comment]
deleting seems to be working, idk if it works as nonhost however

**Comment by TheGreenBandit** [comment]
it seems that the current way i have for setting host just wont work. ill look into it more but will probably get rid of it for this pr

**Comment by TheGreenBandit** [comment]
im going to go to sleep but maybe GrabbableObject.ChangeOwnershipOfPropServerRPC will work, untargetable can be improved by patching the PlayerTripWebServerRpc to do nothing

**Comment by TheGreenBandit** [comment]
Can someone test carrydeadbody?

**Comment by TheGreenBandit** [comment]
once that is tested and confirmed working the only 2 things left to do are find out why items with spaces dont wanna spawn and how to display the itemname of a object for the deleteobject

**Comment by TheGreenBandit** [comment]
I suggest when adding prs to squash and merge this way the commit history doesn't appear with it. Cause this branch has a lot lol

**Comment by TheGreenBandit** [comment]
if you would like to test yet dont want to build [go here to download] (https://github.com/TheGreenBandit/Project-Apparatus/releases/tag/tag)

**Comment by TheGreenBandit** [comment]
Oh shit i forgot to add back changelog n shit

**Comment by zfs266192** [comment]
> 有人可以測試搬運屍體嗎？

I can

**Comment by zfs266192** [comment]
Carry dead body didnt work

**Comment by TheGreenBandit** [comment]
> Carry dead body didnt work

Alright, thanks for testing, I'll look into it

**Comment by Toaaa** [comment]
Why did you remove the credits or are they just not loading for me?
image

**Comment by TheGreenBandit** [comment]
> Oh shit i forgot to add back changelog n shit

Forgot to add back, was debugging

**Comment by Toaaa** [comment]
Looks awesome! Do you guys want to make any changes or can I merge it?

**Comment by TheGreenBandit** [comment]
> Looks awesome! Do you guys want to make any changes or can I merge it?

Carry dead body needs to be fixed other than that it's ready to go, i might just look at how the player grabs objects then use that to make a grabbing function that we could use for future features too

**Comment by TheGreenBandit** [comment]
https://github.com/TheGreenBandit/Project-Apparatus/releases/tag/updateddeadbody new dll incase yall dont wanna build

**Comment by zfs266192** [comment]
Still doesn't work

**Comment by TheGreenBandit** [comment]
might be an issue with how im getting the dead body, ill remove it from the pr and then ill look into adding it in another pr as this is ready without it

**Comment by TheGreenBandit** [comment]
ok seems the pickup works, just dont go in your hands or have any of that function.

**Comment by TheGreenBandit** [comment]
should be ready to go, leaving pickup util in so it can be fixed just as the host override.

**Comment by Toaaa** [comment]
> should be ready to go, leaving pickup util in so it can be fixed just as the host override. Also noticed a game bug (not menu bug) that if u can a item with a worth of 10k or more it breaks the scanner

Teleport All Items doesn't seem to work in your branch 🤷‍♀️

**Comment by TheGreenBandit** [comment]
> > should be ready to go, leaving pickup util in so it can be fixed just as the host override. Also noticed a game bug (not menu bug) that if u can a item with a worth of 10k or more it breaks the scanner
> 
> 
> 
> Teleport All Items doesn't seem to work in your branch 🤷‍♀️

Hm ill look into it when i get home, i think i modified it testing something and forgot to revert it back

**Pull request merged**
