### PR TITLE
Add AntiKick

### PR DESCRIPTION
**Pull request by lylyisbae**
Added AntiKick to Misc Tab. Makes you “nameless”.

### CODE REVIEW

**Comment by KaylinOwO** [comment]
Had to immediately revert, should've reviewed properly beforehand.
the entire Utils.cs file is fked lol

**Comment by lylyisbae** [comment]
Wait what? It's perfectly fine for me? Haha

**Comment by lylyisbae** [comment]
> Had to immediately revert, should've reviewed properly beforehand.
> 
> the entire Utils.cs file is fked lol

I will go and check it again to see what's broken. I do know that there is a draw issue with player ESP where it won't show player esp until someone joins the game

**Comment by KaylinOwO** [comment]
Utils.cs is just Patches.cs 
image

**Comment by lylyisbae** [comment]
> Utils.cs is just Patches.cs image

oh yeah i see! i may have accidentally alt entered and misclicked a quick 'fix' in which it broke some things.

when its completely fixxed im gonna try add commands for invisibility and more. stille not a pro at C# but i just need to spend more time reviewing

**Comment by lylyisbae** [comment]
I figured out the issue with Displaying the player esp

"""Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ProjectApparatus.Hacks.<DisplayPlayers>b__14_1 (GameNetcodeStuff.PlayerControllerB playerControllerB) (at <d093d191fb534a62802eb71c01972a19>:0)
ProjectApparatus.Hacks.DisplayObjects[T] (System.Collections.Generic.IEnumerable`1[T] objects, System.Boolean shouldDisplay, System.Func`2[T,TResult] labelSelector, System.Func`2[T,TResult] colorSelector) (at <d093d191fb534a62802eb71c01972a19>:0)
ProjectApparatus.Hacks.DisplayPlayers () (at <d093d191fb534a62802eb71c01972a19>:0)
ProjectApparatus.Hacks.OnGUI () (at <d093d191fb534a62802eb71c01972a19>:0)"""

if anyone wants to give a hand to patch this or help me understand this id be grateful :3

**Pull request merged**
