### PR TITLE
Added a server tab

### PR DESCRIPTION
**Pull request by Beerian**
now you can get the lobby id and connect to it (doesn't work when the host already landed the ship)

- I haven't tested if you can still connect to someone that went to a friends only lobby

also
- fixed the invisible unlock all suits text

### CODE REVIEW

**Comment by Toaaa** [comment]
> 
I think you're missing some text

**Comment by TheGreenBandit** [comment]
Looks like they didnt add the strings to the langauges. Thats why

**Comment by Beerian** [comment]
it should be all good now, forgot to add the en_US.resx

**Comment by Beerian** [comment]
image
image

**Comment by Toaaa** [comment]
Merged

**Pull request merged**
