### PR TITLE
Added tons of shit

### PR DESCRIPTION
**Pull request by TheGreenBandit**
solves #111 
solves #110 
solves "Adding Specific Monsters/Enemies", "Enemy Spawner", "Spawn spesific enemies" on discord
Added "Spawning Spider Webs" on discord

### CODE REVIEW

**Comment by TheGreenBandit** [comment]
needs review

**Comment by Toaaa** [comment]
Your branch is outdated because I just merged https://github.com/KaylinOwO/Project-Apparatus/pull/115. Please Update

**Comment by TheGreenBandit** [comment]
this is all updated, tested in game, it does have weird behavior in that it wont show on the main online screen until after you join/host a game, but other than that it works just fine

**Comment by Toaaa** [comment]
Merged

**Pull request merged**
