### PR TITLE
Add support language.

### PR DESCRIPTION
**Pull request by udkx**
Added language selection button in settings tab.
Add 2 language dictionary RU and EN.
Replaced all text with variables with text.

I plan to improve the translation into Russian, fix visual bugs not crit (text does not fit into frames, etc.) over the weekend.

### CODE REVIEW

**Review by AnonGajo — CHANGES_REQUESTED** [review]
Looks good, though what is the point in the `ru-RU.txt` file? Address or remove it, and I'll approve the PR 😁 Great work

**Comment by JadeVain** [comment]
Done. I'll think about implementing a separate tab for translating to other languages, but I doubt I can do "on-the-fly" translation to the system languages.

**Comment by tedzify** [comment]
Would it be possible to make the language selection a drop-down? It would be much better as more languages get added eventually the menu would get cluttered, a drop-down solves that.

**Comment by JadeVain** [comment]
> Would it be possible to make the language selection a drop-down? It would be much better as more languages get added eventually the menu would get cluttered, a drop-down solves that.

I'll definitely consider a language dropdown and a separate tab in the next commit

**Comment by JadeVain** [comment]
RIght now, so buggy
image

**Comment by JadeVain** [comment]
Last commit on this branch, next i create new PR with new feature, dropdown menu and new lang tab in UI

**Comment by Taogun** [comment]
only menu?can esp??

**Comment by JadeVain** [comment]
> only menu?can esp??

what u mean, "can esp?"?

**Comment by Taogun** [comment]
display of enemies and items

**Comment by JadeVain** [comment]
> display of enemies and items

But the ESP is already in the project

**Comment by JadeVain** [comment]
Well, that's the fate of Open Source xD

**Comment by Taogun** [comment]
Please point out where code was added

**Comment by Taogun** [comment]
about esp

**Comment by Taogun** [comment]
> The developers stopping updates in the past few days could be related to this kind of pirated sales behavior.

In the words of some Chinese authors, "If it is open source, it can be used for anything."

**Comment by Taogun** [comment]
image
how to achieve like this？？

**Comment by JadeVain** [comment]
> image how to achieve like this？？

replace original titles with translated ones in project

**Comment by Taogun** [comment]
But I can't search the original text of esp in any file. How can I replace it?

**Comment by Taogun** [comment]
i cant find where they are

**Comment by Taogun** [comment]
Then if so, you can send the relevant information to my mailbox, 3256572609@qq.com.
I promise I'm doing this to improve my experience, not to profit from it，thank you for all

**Comment by AnonGajo** [comment]
Apologies for the late response. have been busy. ensure there are no merge conflicts and it's working properly and I'll get it merged today 😁

**Comment by JadeVain** [comment]
> Apologies for the late response. have been busy. ensure there are no merge conflicts and it's working properly and I'll get it merged today 😁

xD, kk 10 min

**Comment by JadeVain** [comment]
> Apologies for the late response. have been busy. ensure there are no merge conflicts and it's working properly and I'll get it merged today 😁

GG, done

**Review by AnonGajo — APPROVED** [review]
Looks good

**Comment by chuxiaaaa** [comment]
> image如何实现这样的目标？？

[https://github.com/KaylinOwO/Project-Apparatus/pull/91](url)

**Pull request merged**
