### PR TITLE
[v1.2.1] Added many things <3

### PR DESCRIPTION
**Pull request by realbillie**
[v1.2.1]

• [+] Added 'Scripts' folder to source files.
• [+] Added 'Kill all Players' to Players tab.
• [+] Added support for '/commands' in chat.
• [+] Added 'AntiRadar' to Self tab.
• [+] Re-Added 'Anti-Kick'.
• [/] Patched bug with Anti-Kick breaking Player ESP.

### CODE REVIEW

**Comment by Toaaa** [comment]
Looks pretty cool!

**Comment by TheGreenBandit** [comment]
I see you are taking your fork in a different direction the main repo is going. When adding things to the main repo, create a branch and add the stuff you want to add there, make sure it all builds, then create a pull request from that branch, as currently your pushes cause issues with building from missing files

**Comment by realbillie** [comment]
Thanks, yeah I'm new to GitHub so I don't really know how to do that. I apologize for the inconvenience :/

**Comment by HermyHerman** [comment]
> I see you are taking your fork in a different direction the main repo is going. When adding things to the main repo, create a branch and add the stuff you want to add there, make sure it all builds, then create a pull request from that branch, as currently your pushes cause issues with building from missing files

Is there a current fix to make this fork work or is it dependent on realbillie?

**Comment by realbillie** [comment]
If someone could please help me out in fixing a few things it would be awesome!! I'm working so much I have little to no time to even get back to my computer. I do have Tuesday and Wednesday off (AEST) which will be plenty of time to fix it and the bugs too (kill all players little buggy)

**Comment by HermyHerman** [comment]
> If someone could please help me out in fixing a few things it would be awesome!! I'm working so much I have little to no time to even get back to my computer. I do have Tuesday and Wednesday off (AEST) which will be plenty of time to fix it and the bugs too (kill all players little buggy)

I wish I could but I never done anything like this, ever. I'm sorry I can't help :(. But good luck at it

**Comment by realbillie** [comment]
> > If someone could please help me out in fixing a few things it would be awesome!! I'm working so much I have little to no time to even get back to my computer. I do have Tuesday and Wednesday off (AEST) which will be plenty of time to fix it and the bugs too (kill all players little buggy)
> 
> I wish I could but I never done anything like this, ever. I'm sorry I can't help :(. But good luck at it

Thanks to Kanon, he fixxed the Kill all players. now all thats left is to fix the scripts for those commands. hopefully be done soon. then will add in the latest changes.

**Comment by HermyHerman** [comment]
I saw a comment of yours saying to message you on Discord for the anti-kick. Which Discord are you on? And would you be able a step--by-step guide on how to add it to the repository? If it's too much, I'd understand if you didn't want to do that

**Comment by realbillie** [comment]
I won't be allowing the new features to be updated to the main repo if that's what you're asking. Simply because I don't agree with the languages recent pull

**Comment by TheGreenBandit** [comment]
> I won't be allowing the new features to be updated to the main repo if that's what you're asking. Simply because I don't agree with the languages recent pull

In your clone, you say chinese resellers will copy this menu, let me tell u there are way better menus to sell than this lol, if you build up a menu enough eventually it will gain a footprint that will be hard to change, for example https://github.com/yimmenu/yimmenu. So in my opinion if people resell it dont matter as many will recognize it as coming from here lol

**Comment by HermyHerman** [comment]
> I won't be allowing the new features to be updated to the main repo if that's what you're asking. Simply because I don't agree with the languages recent pull

I know but I was asking if you could help me add the anti-kick through Discord. I can't find it now but I saw you commented that if we messaged you through Discord, you'd give us that feature

**Comment by realbillie** [comment]
LyLyisbae on discord

**Pull request closed without merging**
