### PR TITLE
Some additions

### PR DESCRIPTION
**Pull request by Toaaa**
I discovered your project on [UnKnoWnCheaTs](https://www.unknowncheats.me/forum/other-fps-games/616587-project-apparatus-lethal-company-cheat.html) a few days ago and thought it was great. Then I noticed that it's open source, so I thought I'd contribute something. Here I have added and improved a few things. Below you can find a list of my changes.

- [+] Added `Teleport all Items`
- [+] Added `Unlock all suits`
- [+] Added missing ESP Tooltips
- [+] Added `Changelog` at `Start`
- [+] Added `Credits` at `Start`
- [+] Added `Start` Section
- [+] Added Dark Mode
- [/] Improved `GameObjectManager`
- [/] Moved assemblies from `bin\` to `lib\`

### CODE REVIEW

**Comment by KaylinOwO** [comment]
Great stuff but please don't include any binaries (e.g: Assembly-CSharp, etc), UC doesn't allow GitHub repos that contain binaries.

**Comment by Toaaa** [comment]
Hey. I just removed all the DLLs. You should now be able to merge my pull request into main.

**Comment by AnonGajo** [comment]
Code looks great! Love the improvements and thank you for removing the unnecessary.
However, it seems there are issues after compiling and injecting, unless I'm compiling incorrectly.
image

**Comment by Toaaa** [comment]
Hi, when I compile it everything works just fine. Maybe Github has messed something up, or the problem is in the relative paths (`..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\`) that you guys added.
Maybe try to clone my repo and use the `lib\` paths.

Discord Name: toaaaa

[Project-Apparatus-main.zip](https://github.com/KaylinOwO/Project-Apparatus/files/13796192/Project-Apparatus-main.zip)

**Comment by AnonGajo** [comment]
> > Code looks great! Love the improvements and thank you for removing the unnecessary. However, it seems there are issues after compiling and injecting, unless I'm compiling incorrectly.
> 
> Hi, when I compile it everything works just fine. Maybe Github has messed something up, or the problem is in the relative paths (`..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\`) that you guys added. Maybe try to clone my repo again now and use the `lib\` paths.
> 
> Discord Name: toaaaa
> 
> Screenshot

I see, works perfectly! Great work!

**Review by AnonGajo — APPROVED** [review]
Great improvements! Thank you for contributing.

**Pull request merged**
